### ISSUE TITLE
Error raised in running Queued Tracking test

### ISSUE THREAD

**Issue by infomotions** [piwik/plugin-QueuedTracking#149] opened 2021-04-29 12:14 UTC
Using Matomo 4.2.1 with latest QueuedTracking plugin

## Expected Behavior
Test completes successfully.

## Current Behavior
In a working redis/queued tracking environment we get the following on one of our setups when running the following command:

./console queuedtracking:test

Settings that will be used:
Backend: redis
NumQueueWorkers: 4
NumRequestsToProcess: 1
ProcessDuringTrackingRequest: 0
QueueEnabled: 0

Redis backend only settings (does not apply when using MySQL backend):
Host: <removed>
Port: 6379
Timeout: 0
Password: <removed>
Database: <removed>
UseSentinelBackend: 0
SentinelMasterName: <removed>

Version / stats:
PHP version: 8.0.3
Uname: <removed>
PHPRedis version: 5.3.4
Backend version: 4.0.14
Memory: array (
  'used_memory' => 122822872,
  'used_memory_human' => '117.13M',
  'used_memory_rss' => 141688832,
  'used_memory_rss_human' => '135.13M',
  'used_memory_peak' => 148505504,
  'used_memory_peak_human' => '141.63M',
  'used_memory_peak_perc' => '82.71%',
  'used_memory_overhead' => 101776860,
  'used_memory_startup' => 648784,
  'used_memory_dataset' => 21046012,
  'used_memory_dataset_perc' => '17.23%',
  'used_memory_lua' => 40960,
  'maxmemory' => 6100000000,
  'maxmemory_reservation' => 200000000,
  'maxfragmentationmemory_reservation' => 300000000,
  'maxmemory_desired_reservation' => 200000000,
  'maxfragmentationmemory_desired_reservation' => 300000000,
  'maxmemory_human' => '5.68G',
  'maxmemory_policy' => 'allkeys-lru',
  'mem_allocator' => 'jemalloc-4.0.3',
)
Uncaught exception in /path_to_matomo/plugins/QueuedTracking/Commands/Test.php line 221:
array_shift(): Argument matomo-org/matomo#1 ($array) must be of type array, bool given

**Comment by flamisz** [comment] 2021-04-29 22:15
Hi @infomotions, thanks for reporting the issue. 

I transferred it into the plugin's repository.

I looked into this error and it looks like somehow `maxmemory-policy` is missing (and the code does not prepared for this, we can fix that).

Are you able to check that redis config in your environment?

One way is to run the `redis-cli` and run `config get maxmemory-policy`. Just to be sure please run `config get maxmemory` too.

Let us know if you were able to check your config.

**Comment by gcompienne-cafex** [comment] 2024-02-20 14:15
Just for info. Still seeing that problem on Matomo 5.0.2 (using the QueuedTracking plugin version 5.0.2).

Test Redis was a AWS Elasticache instance. 

Using the Redis-cli via the info command, I tried to look for the `maxmemory-policy` value but I could not find it either.

However, I was able to find it as `maxmemory_policy:volatile-lru`.

So I do wonder if this has not been caused by a simple typo (dash instead of underscore).

**Comment by gcompienne-cafex** [comment] 2024-02-20 14:20
> Just for info. Still seeing that problem on Matomo 5.0.2 (using the QueuedTracking plugin version 5.0.2).
> 
> Test Redis was a AWS Elasticache instance.
> 
> Using the Redis-cli via the info command, I tried to look for the `maxmemory-policy` value but I could not find it either.
> 
> However, I was able to find it as `maxmemory_policy:volatile-lru`.
> 
> So I do wonder if this has not been caused by a simple typo (dash instead of underscore).

Changing the config param name has not helped either (still exact same error). So probably more than just a typo.

**Comment by AltamashShaikh** [comment] 2024-02-28 03:54
@gcompienne-cafex Can you please paste the error you are getting when you are running the command ?
You can  also try `./console queuedtracking:test -vvv` to get more info

**Comment by gcompienne-cafex** [comment] 2024-02-29 12:47
> @gcompienne-cafex Can you please paste the error you are getting when you are running the command ? You can also try `./console queuedtracking:test -vvv` to get more info

Here you go. But admittedly I am getting the exact same result as what was posted when this ticket was created.

It should also be noted that the queue is active and working fine. Only the test function itself is broken!

```
www-data:~/html$ ./console queuedtracking:test -vvv
Settings that will be used:
Backend: redis
NumQueueWorkers: 1
NumRequestsToProcess: 1
ProcessDuringTrackingRequest: 1
QueueEnabled: 1

Redis backend only settings (does not apply when using MySQL backend):
Host: tls://xxxxx-blanked
Port: 6379
Timeout: 0
Password: xxxxx-blanked
Database: 1
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 8.2.15
Uname: xxxxx-blanked
PHPRedis version: 6.0.2
Backend version: 7.0.7
Memory: array (
  'used_memory' => 6218200,
  'used_memory_human' => '5.93M',
  'used_memory_rss' => 10731520,
  'used_memory_rss_human' => '10.23M',
  'used_memory_peak' => 6544848,
  'used_memory_peak_human' => '6.24M',
  'used_memory_peak_perc' => '95.01%',
  'used_memory_overhead' => 6169424,
  'used_memory_startup' => 6100928,
  'used_memory_dataset' => 48776,
  'used_memory_dataset_perc' => '41.59%',
  'allocator_allocated' => 8388904,
  'allocator_active' => 9555968,
  'allocator_resident' => 14807040,
  'used_memory_lua' => 36864,
  'used_memory_vm_eval' => 36864,
  'used_memory_lua_human' => '36.00K',
  'used_memory_scripts_eval' => 448,
  'number_of_cached_scripts' => 2,
  'number_of_functions' => 0,
  'number_of_libraries' => 0,
  'used_memory_vm_functions' => 32768,
  'used_memory_vm_total' => 69632,
  'used_memory_vm_total_human' => '68.00K',
  'used_memory_functions' => 184,
  'used_memory_scripts' => 632,
  'used_memory_scripts_human' => '632B',
  'maxmemory' => 402653184,
  'maxmemory_human' => '384.00M',
  'maxmemory_policy' => 'volatile-lru',
  'allocator_frag_ratio' => 1.14,
  'allocator_frag_bytes' => 1167064,
  'allocator_rss_ratio' => 1.55,
  'allocator_rss_bytes' => 5251072,
  'rss_overhead_ratio' => 0.72,
  'rss_overhead_bytes' => -4075520,
  'mem_fragmentation_ratio' => 1.74,
  'mem_fragmentation_bytes' => 4552280,
  'mem_not_counted_for_evict' => 0,
  'mem_replication_backlog' => 0,
  'mem_total_replication_buffers' => 0,
  'mem_clients_slaves' => 0,
  'mem_clients_normal' => 67864,
  'mem_cluster_links' => 0,
  'mem_aof_buffer' => 0,
  'mem_allocator' => 'jemalloc-5.1.0',
  'active_defrag_running' => 0,
  'lazyfree_pending_objects' => 0,
  'lazyfreed_objects' => 0,
)
Uncaught exception in /var/www/html/plugins/QueuedTracking/Commands/Test.php line 222:
array_shift(): Argument #1 ($array) must be of type array, bool given
www-data:~/html$ 
```

**Comment by AltamashShaikh** [comment] 2024-02-29 13:07
@gcompienne-cafex Does `redis-cli config get maxmemory-policy` works for you or  `redis-cli config get maxmemory_policy` works for you ?

If `maxmemory_policy` works for you, does changing [this](https://github.com/matomo-org/plugin-QueuedTracking/blob/5.x-dev/Commands/Test.php#L107) line of code with below line works for you ?
```
$evictionPolicy = $this->getRedisConfig($redis, 'maxmemory_policy');
```

**Comment by gcompienne-cafex** [comment] 2024-02-29 13:29
> @gcompienne-cafex Does `redis-cli config get maxmemory-policy` works for you or `redis-cli config get maxmemory_policy` works for you ?
> 
> If `maxmemory_policy` works for you, does changing [this](https://github.com/matomo-org/plugin-QueuedTracking/blob/5.x-dev/Commands/Test.php#L107) line of code with below line works for you ?
> 
> ```
> $evictionPolicy = $this->getRedisConfig($redis, 'maxmemory_policy');
> ```

Ok, so changing the line had no effects, still getting:
```
Uncaught exception in /var/www/html/plugins/QueuedTracking/Commands/Test.php line 222:
array_shift(): Argument #1 ($array) must be of type array, bool given
```

But I have to admit that, so far, when using the redis-cli I was getting that config param by doing the `info memory` command.

When I tried the exact command you requested I got a failure:
```
127.0.0.1:9090> config get maxmemory_policy
(error) ERR unknown command 'config', with args beginning with: 'get' 'maxmemory_policy'
```

Apparently this is because Redis recommends that the command `CONFIG` should be disabled when requiring secure access. And that is true of all Hosted Redis service (and in particular of AWS Elasticache's Redis, which we use).

I suspect the test function will have to use the info capability to get that information. Other projects have been having the same problem (See https://github.com/spring-projects/spring-session/issues/124 ).

**Comment by AltamashShaikh** [comment] 2024-02-29 13:33
@gcompienne-cafex What if you comment this 2 [lines](https://github.com/matomo-org/plugin-QueuedTracking/blob/5.x-dev/Commands/Test.php#L107..L108) from your code ? It will work and the plugin should also work seamlessly, its just printing the maxmemory-policy and doesn't use it anywhere else

**Comment by gcompienne-cafex** [comment] 2024-02-29 13:42
> lines

I removed the two lines you suggested and I got this error instead:

```
The eviction policy can likely lead to errors when memory is low. We recommend to use eviction policy allkeys-lru or alternatively noeviction. Read more here: http://redis.io/topics/lru-cache
Uncaught exception in /var/www/html/plugins/QueuedTracking/Commands/Test.php line 219:
array_shift(): Argument #1 ($array) must be of type array, bool given
```

But it worked if I also removed lines 114 and 115 (as well as lines 107 and 108), i.e I also had to remove these lines:
```
            $evictionPolicy = $this->getRedisConfig($redis, 'maxmemory');
            $output->writeln('MaxMemory config: ' . $evictionPolicy);
```

And then it worked:
```
www-data:~/html$ ./console queuedtracking:test
Settings that will be used:
Backend: redis
NumQueueWorkers: 1
NumRequestsToProcess: 1
ProcessDuringTrackingRequest: 1
QueueEnabled: 1

Redis backend only settings (does not apply when using MySQL backend):
Host: tls://xxxxx-blanked
Port: 6379
Timeout: 0
Password: xxxxx-blanked
Database: 1
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 8.2.15
Uname: xxxxx-blanked
PHPRedis version: 6.0.2
Backend version: 7.0.7
Memory: array (
  'used_memory' => 6220128,
  'used_memory_human' => '5.93M',
  'used_memory_rss' => 10981376,
  'used_memory_rss_human' => '10.47M',
  'used_memory_peak' => 6544848,
  'used_memory_peak_human' => '6.24M',
  'used_memory_peak_perc' => '95.04%',
  'used_memory_overhead' => 6188384,
  'used_memory_startup' => 6100928,
  'used_memory_dataset' => 31744,
  'used_memory_dataset_perc' => '26.63%',
  'allocator_allocated' => 8459848,
  'allocator_active' => 9633792,
  'allocator_resident' => 14884864,
  'used_memory_lua' => 36864,
  'used_memory_vm_eval' => 36864,
  'used_memory_lua_human' => '36.00K',
  'used_memory_scripts_eval' => 448,
  'number_of_cached_scripts' => 2,
  'number_of_functions' => 0,
  'number_of_libraries' => 0,
  'used_memory_vm_functions' => 32768,
  'used_memory_vm_total' => 69632,
  'used_memory_vm_total_human' => '68.00K',
  'used_memory_functions' => 184,
  'used_memory_scripts' => 632,
  'used_memory_scripts_human' => '632B',
  'maxmemory' => 402653184,
  'maxmemory_human' => '384.00M',
  'maxmemory_policy' => 'volatile-lru',
  'allocator_frag_ratio' => 1.14,
  'allocator_frag_bytes' => 1173944,
  'allocator_rss_ratio' => 1.55,
  'allocator_rss_bytes' => 5251072,
  'rss_overhead_ratio' => 0.74,
  'rss_overhead_bytes' => -3903488,
  'mem_fragmentation_ratio' => 1.77,
  'mem_fragmentation_bytes' => 4781904,
  'mem_not_counted_for_evict' => 0,
  'mem_replication_backlog' => 0,
  'mem_total_replication_buffers' => 0,
  'mem_clients_slaves' => 0,
  'mem_clients_normal' => 86824,
  'mem_cluster_links' => 0,
  'mem_aof_buffer' => 0,
  'mem_allocator' => 'jemalloc-5.1.0',
  'active_defrag_running' => 0,
  'lazyfree_pending_objects' => 0,
  'lazyfreed_objects' => 0,
)
The eviction policy can likely lead to errors when memory is low. We recommend to use eviction policy allkeys-lru or alternatively noeviction. Read more here: http://redis.io/topics/lru-cache

Performing some tests:
Redis is connected: 1
Connection works in general
Success for method set(testKey, value)
Success for method setnx(testnxkey, value)
Success for method setex(testexkey, 5, value)
Success for method set(testKeyWithNx, value, array (0 => 'nx',))
Success for method set(testKeyWithEx, value, array ('ex' => 5,))
Initial expire seems to be set correctly
setIfNotExists works fine
expireIfKeyHasValue seems to work fine
Extending expire seems to be set correctly
expireIfKeyHasValue correctly expires only when the value is correct
Expire is still set which is correct
deleteIfKeyHasValue seems to work fine
List feature seems to work fine

Done
www-data:~/html$ 
```

**Comment by AltamashShaikh** [comment] 2024-02-29 13:45
I think we should provide an option to not check `maxmemory-policy` and `maxmemory` config values so that it works for all, will create a PR tomorrow to fix this, meanwhile you can keep using the plugin with the changes you made :+1:

**Comment by AltamashShaikh** [comment] 2024-03-01 05:29
Created #232 to resolve the issue

**Closed as completed** 2024-03-03 22:40 UTC

**Comment by snake14** [comment] 2024-03-03 22:42
@gcompienne-cafex Thank you for your assistance with this issue. The fix has been merged and should be released as part of our regular release schedule, next Monday.

**Comment by gcompienne-cafex** [comment] 2024-03-04 10:50
No Prob. Thanks for your help 👍

**Comment by AltamashShaikh** [comment] 2024-03-10 21:03
@gcompienne-cafex The new command would be `./console queuedtracking:test --skip-max-memory-config-check=1`
