### ISSUE TITLE
Sentinel support to set up HA

### ISSUE THREAD

**Issue by quba** [piwik/plugin-QueuedTracking#23] opened 2015-11-09 10:59 UTC
Hi,

the goal of this ticket is to investigate what needs to be done to support Redis Sentinel.

**Comment by tsteur** [comment] 2015-11-16 19:23
[phpredis](https://github.com/phpredis/phpredis) does not support Sentinel. We're using phpredis so far as it is a PHP extension and therefore faster than the other PHP Redis clients that are written in PHP and not in C. The QueuedTracking was built in mind with being able to switch the backend. Meaning we could fairly easy add another Redis backend adapter and let users choose between them. There's eg https://github.com/colinmollenhour/credis and https://github.com/jamescauwelier/PSRedis which both claim to support Redis Sentinel. The backend is pretty stupid and only forwards calls to Redis, so shouldn't be much work to build. Most work would be most likely setting up Sentinel locally and on travis and testing it

**Comment by tsteur** [comment] 2016-01-13 21:18
Would it be ok to configure Sentinel for QueuedTracking in `config.ini.php` or does it have to be in the UI?

**Comment by tsteur** [comment] 2016-01-13 21:28
I had a look at several PHP redis sentinel projects. We'll have to try to use https://github.com/colinmollenhour/credis first as it supports PHP 5.3. Others require at least PHP 5.4. It seems to be also the most active project with most contributors and still maintained etc.

**Comment by quba** [comment] 2016-01-13 21:39
We prefer config.ini.php

**Comment by tsteur** [comment] 2016-01-14 00:46
I pushed a different backend here: https://github.com/piwik/plugin-QueuedTracking/pull/31

It should be possible to use it by setting this in `config.ini.php`: https://github.com/piwik/plugin-QueuedTracking/pull/31/files#diff-04c6e90faac2675aa89e2176d2eec7d8R131

```
 [QueuedTracking]
 backend=sentinel
 ```

Do you need to configure more than one "master"? Can you ask the sysadmins to give it a try?

**Comment by ChristianGfK** [comment] 2016-04-11 11:29
I was about to give QueuedTracking a try with redis, and ended up here.

The entire point of having sentinels deployed is that you can ask any of them about the current state of the server(s) they monitor. So being able to only specify one sentinel seems kind of... pointless?
If it dies, you're in the same situation as if you had specified just one regular redis server and it dies.

So yes, being able to specify multiple sentinels when using the sentinel backend seems to be almost obligatory.

**Comment by mattab** [comment] 2016-04-11 11:45
@ChristianGfK Support for Sentinel was implemented already in QueuedTracking version 0.3.0 - see `How can I configure the QueuedTracking plugin to use Sentinel?` in https://github.com/piwik/plugin-QueuedTracking#readme

**Comment by mattab** [comment] 2016-04-11 11:46
I re-open as we can leave issue opened until at least one user has confirmed sentinel support is working.

**Comment by ChristianGfK** [comment] 2016-04-11 15:15
@mattab I think you misunderstood my point (or I misunderstood @tsteur's question regarding multiple masters):
When using sentinels, it's not useful to just specify one. For example, we currently have 5. For a sentinel setup to make sense, I should be able to specify all 5. The client should try connecting to one of them until it finds one that works and ask it who the master of the monitored redis instance is. Speaking of which, there's no way to specify that. Sentinels can watch over multiple distinct redis instances.

Regarding "does it work at all":
It doesn't seem to.

As soon as I set the `backend=sentinel`, it stops working.
`console queuedtracking:test` reports   `  Connection to Redis failed after 1 failures.Last Error : (110) Connection timed out`

backend=redis + port 6379: ok
backend=redis + port 26379: errors (obvious sentinels don't accept regular redis commands)
backend=sentinel + port 6379: supposedly timeout
backend=sentinel + port 26379: supposedly timeout

**Comment by tsteur** [comment] 2016-04-11 20:54
That's what I thought to and that's why I asked for it :)

Wasn't 100% sure though as it also sounds like there is some kind of auto-discover or something. But having a single point of entry doesn't sound like failover. It says in http://redis.io/topics/sentinel : 

> Automatic failover. If a master is not working as expected, Sentinel can start a failover process where a slave is promoted to master, the other additional slaves are reconfigured to use the new master, and the applications using the Redis server informed about the new address to use when connecting.
> Configuration provider. Sentinel acts as a source of authority for clients service discovery: clients connect to Sentinels in order to ask for the address of the current Redis master responsible for a given service. If a failover occurs, Sentinels will report the new address.

`backend=sentinel + port 26379:` this *should* work. Which redis version are you using? Can you see some log messages either in redis or system logs or so?

**Comment by tsteur** [comment] 2016-04-11 20:58
From https://github.com/colinmollenhour/credis:

> Redis Sentinel is a system that can monitor Redis instances. You register master servers and Sentinel automatically detects its slaves.

The auto discovery is currently not implemented in the plugin as not sure how it is supposed to discover slaves automatically when master is down anyway.

**Comment by quba** [comment] 2016-04-12 10:31
So, what are the further steps to have full sentinel support?

**Comment by quba** [comment] 2016-04-12 10:32
cc @jaceklubzinski

**Comment by ChristianGfK** [comment] 2016-04-12 11:08
Turns out Credis already has an open issue on this, with a workaround that could be done in the software using Credis (which in this case is, of course, this plugin): https://github.com/colinmollenhour/credis/issues/46

And, looking further, it looks like you already tried doing just that, @tsteur?
https://github.com/colinmollenhour/credis/issues/52

Maybe just revisiting that would be enough to enable "multiple sentinel" support (which, if I understand redis' official docs correctly, is really the only way that makes sense for a HA setup).



As to why it doesn't even seem to work with one sentinel, I'm not sure.
To my understanding, the process should look like this:

1. Connect to configured sentinel(s).
2. Request the address of the current master for the configured redis "group" using `SENTINEL get-master-addr-by-name groupname`.
3. Connect there and do whatever it is that needs doing.

This seems to match both https://github.com/colinmollenhour/credis#automatic-failover-with-sentinel and http://redis.io/topics/sentinel.

There is currently no way to specify the name of the group, so adding that seems necessary.
Which seems to have pointed me in the right direction: It looks like the Sentinel backend goes from connecting to the sentinel straight to trying to connect to redis, without actually asking the sentinel for the master's address: https://github.com/piwik/plugin-QueuedTracking/blob/master/Queue/Backend/Sentinel.php#L23
That particular step is outlined in the Credis readme, linked above.


Sorry for the stream-of-thought style. ;-)

**Comment by ChristianGfK** [comment] 2016-04-12 11:24
_(Decided to put this into a separate comment, because it looks like I found the actual problem in my previous comment.)_

I'm currently using redis version: 2.8.23 (for both redis and the sentinels).

@tsteur: You seem to have misunderstood the "slave auto-discovery" thing.
That is something that happens within the redis sentinel construct. It's not something you need to do/implement. You can ask the sentinels about the state of the group you're interested in with the `SENTINEL slaves groupname` and `SENTINEL sentinels groupname` commands.

The full list of sentinel commands is available here: http://redis.io/topics/sentinel#sentinel-commands
But they are abstracted by Credis anyway.

I think the only command a regular "I want to know which redis instance to talk to" client really ever needs to use is `SENTINEL get-master-addr-by-name groupname`.
(And maybe it should handle the case where that doesn't give a result, which would probably indicate that the group failed/there is no master to write to.)

N.b.: I'm using "group" here, because using "cluster" for a group of 1 master and 1 or more slaves seems confusing, because redis also has an actual clustering feature that is not strictly related.

**Comment by ChristianGfK** [comment] 2016-04-12 16:28
[I worked out a fix locally](https://github.com/ChristianGfK/plugin-QueuedTracking/commit/e9c11d970c4728a52367be0f8267cd716155ec17), that I'm sure can be adapted to fit properly into Piwik's plugin structure.
The name of the redis server group needs to be UI-configurable. The timeout, too, probably, see below.

It failed to work previously for several reasons:

- Piwik set the connect timeout to 0 (_I'm not sure where_), overriding Credis' default of NULL ([in which case it would default to 2.5 s](https://github.com/colinmollenhour/credis/blob/master/Client.php#L428)).
Apparently, 0 is still good enough for a regular connection to work, but not for a Sentinel-based one? Not quite sure on this part.

- Since Sentinels don't support the full range of Redis commands, specifying a database that is not 0 makes it fail, too. [Credis skips issuing the `select` command if the db is 0](https://github.com/colinmollenhour/credis/blob/master/Client.php#L461).

- For the same reason, specifying a password makes it fail, since [Sentinels don't currently support `AUTH`](https://github.com/antirez/redis/issues/1904).

Removing all of these and adding the necessary extra step of asking the Sentinel for the current master's address and then connecting there (see commit) makes it work as expected.

**Comment by ChristianGfK** [comment] 2016-04-12 16:43
Argh.
I only ever tried it with the test command `console queuedtracking:test`.

If I try to change the configuration in the admin panel, I get
> Queue enabled: Connection to Redis failed. Please verify Redis host and port

:frowning: 
I don't really understand why, though?

**Comment by ChristianGfK** [comment] 2016-04-12 17:01
Because [it tries to validate the settings entered in the settings form](https://github.com/piwik/plugin-QueuedTracking/blob/master/Settings.php#L214), and [that in turn tries to use `ECHO`](https://github.com/piwik/plugin-QueuedTracking/blob/master/Queue/Backend/Redis.php#L35), which Sentinels also don't support.
Also, [it looks like it just instantiates an entirely new client, regardless of the configured backend](https://github.com/piwik/plugin-QueuedTracking/blob/a7137646fa4d738c6378686df6cd222fd291217f/SystemCheck.php#L26), but I might be wrong on that.

(I just short-circuited `testConnection()` by making it always return true, and now it works. Clearly not a proper solution. :stuck_out_tongue:)

**Comment by tsteur** [comment] 2016-04-12 20:53
> I don't really understand why, though?

Probably the UI tests hard coded with Redis extension, not credis. credis will be probably only configured in the config for now as we cannot define multiple servers via Piwik settings API etc.

> Since Sentinels don't support the full range of Redis commands, specifying a database that is not 0 makes it fail, too. Credis skips issuing the select command if the db is 0.

I need to look into this.


@ChristianGfK thanks for all this in general. I'm understanding it much better now and it probably indeed confused some server parts with client parts from their doc. In the example code you pasted there is still only one server configured to get the actual master. Don't I need to define multiple servers and it discovers automatically which one is the master?

I will be working on this soon.

**Comment by tsteur** [comment] 2016-04-12 23:13
I issued a pull request and it seems to work now see https://github.com/piwik/plugin-QueuedTracking/pull/39 (still only one sentinel server configured)

**Comment by ChristianGfK** [comment] 2016-04-13 11:20
Regarding "still only one sentinel": Yeah, I didn't try doing that.
That needs at least:

- A way to configure multiple sentinels (multiple, comma-separated?)
- If so, needs some way to explode them into an array
- Code to iterate over them until a reachable one is found ([as suggested by here](https://github.com/colinmollenhour/credis/issues/46#issuecomment-157817598) by @colinmollenhour)
- Probably more things I didn't even think of :wink:

**Comment by tsteur** [comment] 2016-04-13 21:17
OK I can provide a way to either specify one sentinel client via UI or multiple via `config` file maybe. Wouldn't it be a bit "slow" to always try to connect to various sentinels until one found? On the other hand redis is fast and it seems to be the only way to have true high availability. Otherwise there's always a single point of failure.

@quba what's the setup at Piwik PRO? Are there multiple sentinel servers?

**Comment by tsteur** [comment] 2016-04-13 21:30
From http://redis.io/topics/sentinel-clients

> The client should iterate the list of Sentinel addresses. For every address it should try to connect to the Sentinel, using a short timeout (in the order of a few hundreds of milliseconds). On errors or timeouts the next Sentinel address should be tried.
If all the Sentinel addresses were tried without success, an error should be returned to the client.

I'm gonna make it possible to specify multiple sentinels comma separated in the UI

**Comment by tsteur** [comment] 2016-04-13 23:59
I updated #39 to accept multiple sentinel servers. Also all sentinel settings can be now configured via UI as it is more safe as config would need to be configured on each server and there could be likely errors when config files are not the same everywhere. This means when adding a new sentinel only in the UI the setting needs to be changed and not on each server.

Can maybe someone give it a try see https://github.com/piwik/plugin-QueuedTracking/pull/39/files

**Comment by tsteur** [comment] 2016-04-14 00:00
Once sentinel is enabled, multiple hosts and ports can be specified comma separated. There should be an example in the help text for "Redis host"

**Comment by quba** [comment] 2016-04-14 18:52
We have multiple sentinels (3 atm).

**Comment by ChristianGfK** [comment] 2016-04-15 08:24
Works with 4 sentinels for me. :+1:

**Comment by tsteur** [comment] 2016-04-19 02:23
I merged the PR and will release a new version of the plugin. Thanks for your help @ChristianGfK 👍

**Closed by tsteur** 2016-04-19 02:23 UTC
Labels: enhancement

**Comment by ChristianGfK** [comment] 2016-04-19 08:21
My pleasure! Thanks for the awesomeness that is Piwik. :+1:
