### ISSUE TITLE
QueueTracking lock status so long

### ISSUE THREAD

**Issue by danielsss** [piwik/plugin-QueuedTracking#145] opened 2021-01-14 06:48 UTC
I've multiple Matomo containers behind of the load balancer.

Each Matomo container uses an individual Redis as request cache, but I've noticed one worker of them that has been locked for a long time. Also, occurs the same situation on other server nodes.

* Here's one node lock status:

```shell
/var/www/html # ./console queuedtracking:lock-status
"QueuedTrackingLock2" is locked for 29955 ms
Set option --unlock=QueuedTrackingLock2 to unlock the queue.

"QueuedTrackingLock0" is locked for 57902 ms
Set option --unlock=QueuedTrackingLock0 to unlock the queue.

"QueuedTrackingLock1" is locked for 31219609 ms
Set option --unlock=QueuedTrackingLock1 to unlock the queue.

/var/www/html #
```

**_31219609 ms / 1000 / 60 / 60 ~= 8.672113611111111 (hours)_**

* Cache usage & blocked process request

```shell
/var/www/html # ./console queuedtracking:monitor
Queue is enabled
The command ./console queuedtracking:process has to be executed to process request sets within queue
Up to 4 workers will be used
Processor will start once there are at least 30 request sets in the queue
418940 (36486+382345+46+63) request sets left in queue. 868.42M used memory (869.23M peak). 4 workers active.    
/var/www/html #
```

The cron job runs in period of 30 seconds.

```shell
docker exec matomo sh -c "/var/www/html/console queuedtracking:process --queue-id=0" >> archive-report.log
docker exec matomo sh -c "/var/www/html/console queuedtracking:process --queue-id=1" >> archive-report.log
docker exec matomo sh -c "/var/www/html/console queuedtracking:process --queue-id=2" >> archive-report.log
docker exec matomo sh -c "/var/www/html/console queuedtracking:process --queue-id=3" >> archive-report.log
```

I've closed `Process during tracking request` and 4 is the `Number of queue workers`.

I totally have no idea how to deal with it. Please help !

**Comment by danielsss** [comment] 2021-01-14 08:03
I also tried to delete the lock and processes request manually. But failed, it will lock the cache queue again.

```shell
./console queuedtracking:lock-status --unlock=QueuedTrackingLock1

./console queuedtracking:process --queue-id=1
```

**Comment by danielsss** [comment] 2021-01-14 11:22
Tried to process with blocked queue multi times and got result as below:

Executed commands:
```shell
./console queuedtracking:lock-status --unlock=QueuedTrackingLock1
./console queuedtracking:process --queue-id="1" -vvv
```

Result - 1:
```text
[2021-01-14 11:06:29] piwik.ERROR: Fatal error encountered: /var/www/html/plugins/Monolog/Processor/ClassNameProcessor.php(73): Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)  on /var/www/html/plugins/Monolog/Processor/ClassNameProcessor.php(73)  {"exception":{"type":1,"message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)","file":"/var/www/html/plugins/Monolog/Processor/ClassNameProcessor.php","line":73,"backtrace":" on /var/www/html/plugins/Monolog/Processor/ClassNameProcessor.php(73)\n"},"ignoreInScreenWriter":true} {"class":"Piwik\\FrontController","request_id":5269}
```

Result - 2:
```text
[2021-01-14 11:16:00] piwik.DEBUG: Executing Piwik\Plugins\CustomDimensions\Tracker\CustomDimensionsRequestProcessor::processRequestParams()... [] {"class":"QueuedTracking","request_id":5775}
```
Didn't see something like `This worker finished queue processing with *req/s (* requests in * seconds)`

**Comment by tsteur** [comment] 2021-01-14 21:42
@danielsss it might help to increase the memory limit from 128MB to say 256 or 512MB. 

Usually, the locks are released automatically, but if there's some failure like a memory limit then it might not be able to release the lock automatically. The locks are like usually I think around 20-120 sec (haven't checked) but they can be larger if you for example use bulk requests eg by replaying requests from log analytics etc (which in this case it would not be recommended to use queued tracking in case you replay logs from log analytics).

I suggest you increase the memory limit in your PHP setting and check if there's still an issue.

**Comment by danielsss** [comment] 2021-01-15 07:56
@tsteur Thanks for your help.

Actually, the bulk requests is the way that I used and I can try splitting bulk requests to single request. (in my case, the client can't reach the internet sometimes)

I'm wondering about the `Fatal error`, because of the memory limit is not 128M and I already set memory limit to 2048M(checked by Matomo `system check`).

I still have a question. The Matomo server has a individual Redis as request cache(That is, I've multiple Redis nodes and they are not sentinel or master/slave ) . Will this cause some potential problem to Queued Tracking  ?

**Comment by tsteur** [comment] 2021-01-17 23:36
> Actually, the bulk requests is the way that I used and I can try splitting bulk requests to single request. 

This should cause shorter lock times. Ideally, it be great to fix the root cause though as long lock times shouldn't be an issue when the locks get released properly. It did sound to me that there is a memory issue but maybe not. I'd suggest to check again though just because sometimes there's eg a different limit for web and CLI configured or sometimes multiple PHP ini files exist etc. The Matomo system check was probably in the UI (web). On CLI where you execute the queued tracking you can eg check using `php -i | grep memory` (on a linux).

> I still have a question. The Matomo server has a individual Redis as request cache(That is, I've multiple Redis nodes and they are not sentinel or master/slave ) . Will this cause some potential problem to Queued Tracking ?

Yes I think this can cause issues. I suppose you would need on every server a `queuedtracking:process` running but the biggest problem might be that the requests are potentially not replayed in the right order. It is a bit difficult to explain like say 

* tracking request a visit entered your website `/test` processed in redis A on server A
* tracking request a visit viewed `/test2` processed in redis B on server B

If for example the `queuedtracking:process` is faster on server B with redis B then eg a wrong "entry page" might be reported as AFAIK Matomo would think the user entered on page with url `/test2`.

**Comment by danielsss** [comment] 2021-01-18 02:36
@tsteur I appreciated with your explanation.

As you said. I'm using one Redis as shared cache and everything goes well for now.

**Comment by danielsss** [comment] 2021-01-21 07:36
@tsteur  It's happening again and really drives me crazy.

The `--queue-id=0` is blocked.

* Command:  `./console queuedtracking:lock-status --unlock=QueuedTrackingLock0 && ./console queuedtracking:process --queue-id=0 -vvv`

* Error Log:

```shell
...

...

[2021-01-21 07:30:12] piwik.DEBUG: Executing Piwik\Plugins\PagePerformance\Tracker\PerformanceDataProcessor::recordLogs()... [] {"class":"QueuedTracking","request_id":7524}

[2021-01-21 07:30:12] piwik.DEBUG: Executing Piwik\Plugins\CustomDimensions\Tracker\CustomDimensionsRequestProcessor::recordLogs()... [] {"class":"QueuedTracking","request_id":7524}

[2021-01-21 07:30:12] piwik.DEBUG: Failed to expire key QueuedTrackingLock0 (b2be8b818696 / ). It seems like the key already expired as it no longer exists. [] {"class":"QueuedTracking","request_id":7524}

[2021-01-21 07:30:12] piwik.DEBUG: Failed to process a request set: Rolled back during processing as we no longer have lock or the lock was never acquired. So far tracker processed 0 requests [] {"class":"QueuedTracking","request_id":7524}

[2021-01-21 07:30:12] piwik.ERROR: Uncaught exception: /var/www/html/plugins/QueuedTracking/Queue/Processor.php(244): Rolled back during processing as we no longer have lock or the lock was never acquired. So far tracker processed 0 requests Rolled back during processing as we no longer have lock or the lock was never acquired. So far tracker processed 0 requests #0 /var/www/html/plugins/QueuedTracking/Queue/Processor.php(190): Piwik\Plugins\QueuedTracking\Queue\Processor->forceRollbackAndThrowExceptionAsAnotherProcessMightProcessSameRequestSets(Object(Piwik\Tracker), 'processing') #1 /var/www/html/plugins/QueuedTracking/Queue/Processor.php(143): Piwik\Plugins\QueuedTracking\Queue\Processor->processRequestSets(Object(Piwik\Tracker), Array) #2 /var/www/html/plugins/QueuedTracking/Commands/Process.php(86): Piwik\Plugins\QueuedTracking\Queue\Processor->process() #3 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\QueuedTracking\Commands\Process->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #4 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\QueuedTracking\Commands\Process), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 /var/www/html/core/Console.php(130): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /var/www/html/core/Access.php(673): Piwik\Console->Piwik\{closure}() #9 /var/www/html/core/Console.php(131): Piwik\Access::doAsSuperUser(Object(Closure)) #10 /var/www/html/core/Console.php(82): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/html/console(32): Symfony\Component\Console\Application->run() #13 {main} {"exception":"[object] (Piwik\\Plugins\\QueuedTracking\\Queue\\LockExpiredException(code: 0): Rolled back during processing as we no longer have lock or the lock was never acquired. So far tracker processed 0 requests at /var/www/html/plugins/QueuedTracking/Queue/Processor.php:244)","ignoreInScreenWriter":true} {"class":"Piwik\\FrontController","request_id":7524}

[2021-01-21 07:30:12] piwik.DEBUG: Loaded plugins: CoreHome, IntranetMeasurable, Actions, Referrers, UserLanguage, DevicesDetection, Goals, Ecommerce, Events, UserCountry, GeoIp2, VisitTime, VisitorInterest, Login, UsersManager, SitesManager, PrivacyManager, Contents, BulkTracking, Resolution, DevicePlugins, Heartbeat, Marketplace, UserId, PagePerformance, CustomDimensions, QueuedTracking, CorePluginsAdmin, CoreAdminHome, WebsiteMeasurable, Diagnostics, CoreVisualizations, Proxy, API, Widgetize, Transitions, LanguagesManager, Dashboard, MultiSites, SEO, VisitsSummary, VisitFrequency, RssWidget, Feedback, Monolog, TwoFactorAuth, Installation, CoreUpdater, CoreConsole, ScheduledReports, UserCountryMap, Live, ImageGraph, Annotations, MobileMessaging, Overlay, SegmentEditor, Insights, Morpheus, Intl, ProfessionalServices, CustomJsTracker, Tour, DBStats [] {"class":"Piwik\\Plugin\\Manager","request_id":7524}




  [Piwik\Plugins\QueuedTracking\Queue\LockExpiredException]
  Rolled back during processing as we no longer have lock or the lock was never acquired. So far tracker processed 0 requests



Exception trace:
 () at /var/www/html/plugins/QueuedTracking/Queue/Processor.php:244
 Piwik\Plugins\QueuedTracking\Queue\Processor->forceRollbackAndThrowExceptionAsAnotherProcessMightProcessSameRequestSets() at /var/www/html/plugins/QueuedTracking/Queue/Processor.php:190
 Piwik\Plugins\QueuedTracking\Queue\Processor->processRequestSets() at /var/www/html/plugins/QueuedTracking/Queue/Processor.php:143
 Piwik\Plugins\QueuedTracking\Queue\Processor->process() at /var/www/html/plugins/QueuedTracking/Commands/Process.php:86
 Piwik\Plugins\QueuedTracking\Commands\Process->execute() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at n/a:n/a
 call_user_func() at /var/www/html/core/Console.php:130
 Piwik\Console->Piwik\{closure}() at /var/www/html/core/Access.php:673
 Piwik\Access::doAsSuperUser() at /var/www/html/core/Console.php:131
 Piwik\Console->doRunImpl() at /var/www/html/core/Console.php:82
 Piwik\Console->doRun() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/html/console:32


queuedtracking:process [--queue-id="..."] [--force-num-requests-process-at-once="..."]


/var/www/html #
```


* Lock status & monitor

```shell
/var/www/html # ./console queuedtracking:monitor
Queue is enabled
The command ./console queuedtracking:process has to be executed to process request sets within queue
Up to 8 workers will be used
Processor will start once there are at least 15 request sets in the queue
224337 (220192+245+174+740+335+207+1291+1153) request sets left in queue. 500.44M used memory (510.00M peak). 4 workers active.
```

```shell
/var/www/html # ./console queuedtracking:lock-status
"QueuedTrackingLock6" is locked for 33941 ms
Set option --unlock=QueuedTrackingLock6 to unlock the queue.

"QueuedTrackingLock1" is locked for 41861 ms
Set option --unlock=QueuedTrackingLock1 to unlock the queue.

"QueuedTrackingLock3" is locked for 29983 ms
Set option --unlock=QueuedTrackingLock3 to unlock the queue.

"QueuedTrackingLock0" is locked for 2769034 ms
Set option --unlock=QueuedTrackingLock0 to unlock the queue.

"QueuedTrackingLock7" is locked for 29995 ms
Set option --unlock=QueuedTrackingLock7 to unlock the queue.

"QueuedTrackingLock4" is locked for 55891 ms
Set option --unlock=QueuedTrackingLock4 to unlock the queue.
```

**Comment by danielsss** [comment] 2021-01-21 08:55
@tsteur  As I told you before. The client can't reach the internet sometimes, but it will store the request of their operation to local cache. When their network is available, the locally cached request will be sent to the Matomo server. This might contains several days of request. 

Also I tried to run `./console queuedtracking:lock-status --unlock=QueuedTrackingLock0 && ./console queuedtracking:process --queue-id=0 -vvv` repeatedly on the blocked queue and I've noticed some suspect logs as below example :

```shell
[2021-01-21 08:30:02] piwik.DEBUG: Current datetime: 2021-01-19 16:24:12 {"date":"2021-01-19 16:24:12"} {"class":"QueuedTracking","request_id":20828}
```
> The command doesn't exit normally and it looks like a loop that outputs logs from `early(2021-01-19)` to `now(2021-01-21)`.

* Why it does not happen to other queues? The rest of queue works fine.

**Comment by tsteur** [comment] 2021-01-21 21:39
@danielsss great to hear everything goes well for now. So we can close the issue for now?

**Comment by danielsss** [comment] 2021-01-22 05:35
@tsteur I found something that might is not an issue, but it will cause a large queue.

Example:

```shell
/var/www/html # ./console queuedtracking:monitor
Queue is enabled
The command ./console queuedtracking:process has to be executed to process request sets within queue
Up to 8 workers will be used
Processor will start once there are at least 15 request sets in the queue
180977 (180060+12+195+158+120+231+156+45) request sets left in queue. 380.96M used memory (381.71M peak). 3 workers active
```

> The --queue-id=0 is not blocked, but the `queuedtracking:process-request` takes at least ~2000 seconds for ~10000+ requests.
> Also I've decreased the `Number of requests that are processed in one batch` to 1 from 15 and it takes ~500 seconds for 5000+ requests.

```shell
This worker finished queue processing with 11.66req/s (5010 requests in 429.61 seconds)
```


So, I don't know why only occurs this situation on `queue-id=0`(Maybe the issue that is caused by my request. Anyway, I'll keep eyes on it.) 

Do you have any experience dealing with it ?

**Comment by tsteur** [comment] 2021-01-24 00:52
Processing only one at once can be faster especially if you have a lot of bulk requests in the queue (AFAIK each bulk request would be only counted as one even though one bulk request might contain many requests). This could also explain why it takes a while to process these requests.

Without knowing all details and possibly without inspecting all the requests in the queue etc it's unfortunately hard to come to any conclusions. Do a lot of the requests have the same userId or IP address or so? This would explain why many requests or why some specific requests that might cause trouble or take longer go into queueId 0.

**Comment by danielsss** [comment] 2021-01-27 16:23
@tsteur The problem has solved and now, you can close this issue.

I've checked the tracking requests and indeed, there're a lot of the requests that have the same userId or IP address.

Also I've made some adjustments it wouldn't take longer go into queueId 0.

**Comment by tsteur** [comment] 2021-01-27 19:26
Great to hear @danielsss thanks for letting us know 👍

**Closed as completed by tsteur** 2021-01-27 19:26 UTC
Labels: question
