### ISSUE TITLE
Single queue over exceed

### ISSUE THREAD

**Issue by ppongsakorn** [piwik/plugin-QueuedTracking#230] opened 2024-02-08 13:40 UTC
![IMG_2709](https://github.com/matomo-org/plugin-QueuedTracking/assets/3600474/da07ac25-8d7a-471c-96ae-a79d9dbadb0b)

Any recommend to process single queue that over exceed.

**Comment by snake14** [comment] 2024-02-08 19:59
Hi @ppongsakorn . If a single queue is that much larger than all of the others, it makes me think that there's a request that's failing to process and is holding up the whole queue. What version of Matomo and what version of the plugin are you running?

**Comment by ppongsakorn** [comment] 2024-02-09 03:45
Hi @snake14 ,Thank you for reply.

I use  matomo 4.15.1
QueueTracking 4.0.7

When i run ./console queuedtracking:process  --queue-id 12
i will get "This worker finished queue processing with 0req/s (0 requests in 0.25 seconds)" every time.

Can i pause inserting queue to queue id 12, until all request processing complete.

**Comment by snake14** [comment] 2024-02-11 20:37
Hi @ppongsakorn . Thank you for that information. That release has an improvement to skip failed tracking requests and process the rest, so I'm not sure why it would back up so back like that. Do you see any warnings/errors in your Matomo or server logs? I'm not aware of a way to exclude a queue in inserts. Have you tried running `./console queuedtracking:monitor` or tried using the verbose option like this `./console queuedtracking:process --queue-id 12 -vvv`?

**Comment by AltamashShaikh** [comment] 2024-02-20 03:38
@ppongsakorn Can you check the last comment please ?

**Comment by ppongsakorn** [comment] 2024-02-21 04:31
![image](https://github.com/matomo-org/plugin-QueuedTracking/assets/3600474/27ed2bad-dd29-427b-b3ef-18555f841827)

I got infinity loop (long processing, more than 1 hour) when run this command even if a little queue in --queue-id 12

./console queuedtracking:process --queue-id 12 -vvv

I must delete data in queue-id 12 when system notify to reach 100,000.

I don't understand why other queue-id don't effect like this.

**Comment by snake14** [comment] 2024-02-21 20:19
@ppongsakorn This is very strange. The plugin is supposed to skip a request that fails to process so that it doesn't hold up processing of the queue. As [the plugin FAQ](https://plugins.matomo.org/QueuedTracking#faq) suggests, you might want to try running `./console queuedtracking:print-queued-requests --queue-id=12` a few minutes apart and see if it's the same request both times. If it is, there might be something wrong with the request and you could try manually removing it from the queue. Any other ideas @AltamashShaikh ?

**Comment by snake14** [comment] 2024-02-21 20:25
Actually @ppongsakorn , you may run into issues printing the queue as there are so many queued requests. I thought that there was a way to limit the number output, but I'm not seeing one. You may have to access the queue (Redis?) directly and inspect the request at the front of the queue that way.

Edit:
You should be safe running the command. I just confirmed that it only outputs the first batch of requests. So it will only output as many requests as you have configured in the plugin settings:
![image](https://github.com/matomo-org/plugin-QueuedTracking/assets/11394099/de94229f-961e-45a5-bc20-2df2183c4722)

So, please try running `./console queuedtracking:print-queued-requests --queue-id=12` and see if there's anything wrong with the first few requests.

**Comment by AltamashShaikh** [comment] 2024-02-22 03:44
@snake14 Maybe after checking the requests using `/console queuedtracking:print-queued-requests --queue-id=12` command @ppongsakorn can try to delete the 1st request and see if it works

**Comment by ppongsakorn** [comment] 2024-02-23 07:03
@snake14 
I attach first 25 requests in redis , Is normal request?

[request.log](https://github.com/matomo-org/plugin-QueuedTracking/files/14382412/request.log)

**Comment by ppongsakorn** [comment] 2024-02-23 07:06
@AltamashShaikh I delete 100,200 in queues but still same old.

**Comment by snake14** [comment] 2024-02-25 20:35
I don't see anything wrong with those requests. There are quite a few that look like they may be duplicates, but that shouldn't prevent the queue from processing. Do you see anything amiss @AltamashShaikh ?

**Comment by AltamashShaikh** [comment] 2024-02-26 03:16
@ppongsakorn Did you got the first 25 requests via `lRange` command ?
eg: `lrange $key 0 24`

**Comment by ppongsakorn** [comment] 2024-02-27 03:22
> @ppongsakorn Did you got the first 25 requests via `lRange` command ? eg: `lrange $key 0 24`

Check this file,

[request_lrang.log](https://github.com/matomo-org/plugin-QueuedTracking/files/14413866/request_lrang.log)

Thank you.

**Comment by AltamashShaikh** [comment] 2024-02-27 06:27
@ppongsakorn I don't see any issue, I was able to take add the request from `request_lrang.log` file in my local without any issues
![Screenshot from 2024-02-27 11-54-28](https://github.com/matomo-org/plugin-QueuedTracking/assets/14902277/7ff1ca7f-7ea9-44ec-be4d-0c721bccb710)

When you run `./console queuedtracking:process -vvv` do you see any error ?

**Comment by adamreng** [comment] 2024-04-03 03:49
@ppongsakorn Can you check the latest comment?

**Comment by AltamashShaikh** [comment] 2024-04-22 03:36
Closing due to in-activity

**Closed as not planned by AltamashShaikh** 2024-04-22 03:36 UTC
