### ISSUE TITLE
Plugin is not working under Matomo 4

### ISSUE THREAD

**Issue by paladox** [piwik/plugin-QueuedTracking#143] opened 2020-12-12 22:42 UTC
Hi, under Matomo 4, I've noticed this plugin not working.

I don't see Vistors updating even though I've enabled "Process during tracking request".

I've even tried the cron which still doesn't fix it.

Even the live map isn't working when I've enabled this plugin. This was working under Matomo 3.

Our visitor count has also dropped too.

<img width="443" alt="Screenshot 2020-12-12 at 22 41 59" src="https://user-images.githubusercontent.com/5727000/101996533-40e96f80-3ccb-11eb-9a7d-6ddc3c6fec0c.png">

**Comment by tsteur** [comment] 2020-12-13 20:28
Hi @paladox 

We have been using here queued tracking with Matomo 4 without any issues for many sites and different Matomo installations. I also looked through the code but can't see anything that could cause issues right now.

Do you get any requests into the queue? Can you run queuedtracking:process with the` -vvv` option in case it shows some errors or so?

**Comment by lrupp** [comment] 2021-01-07 19:51
I guess the problem is in plugin.json: here it requires "piwik": ">=3.0.0-b1,<4.0.0-b1" - while Matomo/Piwik is meanwhile at version 4.1.0.

The following code change should IMHO fix the problem:

```
Index: LoginFailLog/plugin.json
===================================================================
--- LoginFailLog.orig/plugin.json
+++ LoginFailLog/plugin.json
@@ -3,7 +3,7 @@
     "version": "0.1.1",
     "description": "Logs failed login attempts together with user IP. Useful for protecting Piwik against brute force attacks via fail2ban or similar tools.",
     "require": {
-        "piwik": ">=3.0.0-b1,<4.0.0-b1"
+        "piwik": ">=3.0.0-b1,<5.0.0-b1" 
     },
     "authors": [
         {
```

**Comment by Findus23** [comment] 2021-01-07 19:54
@lrupp 
Are you sure you are using the latest version of the plugin?

The 4.0.x releases of the plugin all support Matomo 4+ and also properly specify this in the plugin.json:

https://github.com/matomo-org/plugin-QueuedTracking/blob/69cc21c6908fc8175c3355230a1f1b459836074b/plugin.json#L9-L11

**Comment by lrupp** [comment] 2021-01-07 20:43
Mea culpa, sorry! 

You are absolutely right: this is not the problem. I had another Matomo plugin (LoginFailLog) in mind when writing this...
=> invalid, sorry.

**Comment by tsteur** [comment] 2021-01-10 19:32
@lrupp Have you maybe updated the LoginFailLog plugin by now? Are all plugins that you are using now up to date? 

When you use `./console queuedtracking:monitor` do you see tracking requests in the queue? It should show if tracking requests are in the queue or not and if more are added or not (the number of requests in the queue would increase).

When you use `./console queuedtracking:process -vvv` do you maybe notice any error messages?

Otherwise if you have access to error logs do you maybe see any errors in the error logs for PHP?

sorry about all the questions but trying to understand things better. Generally the plugin should work fine as we have many users using it successfully and we have also used it ourselves. Last question: Are you using MySQL or Redis as a backend?

**Comment by GieltjE** [comment] 2021-03-02 09:31
Sorry for hijacking this post, but it might be the same issue:

```
./console queuedtracking:monitor
21 (8+13) request sets left in queue. 16.06M used memory (22.49M peak). 0 workers active.
```
```
./console queuedtracking:process -vvvv
Starting to process request sets, this can take a while

This worker finished queue processing with 0req/s (0 requests in 0.00 seconds)
```
But nothing ever gets through, nor does the requests left in queue go down.

**Comment by tsteur** [comment] 2021-03-02 20:06
Hi @GieltjE this might be a different issue. For example it might be worth checking the configured number of tracking requests to be processed at once. For example if this is set to 20, but there are only 8 or 13 requests in each individual queue, then it wouldn't do anything and wait for more tracking requests to be queued.

**Comment by tsteur** [comment] 2021-08-03 21:29
I'll close this issue for now as the plugin should work nicely with Matomo 4 (we're using it ourselves). If anyone is still experiencing an issue please create a new issue as it's likely unrelated Matomo 4. Thanks

**Closed as completed by tsteur** 2021-08-03 21:29 UTC
Labels: question
